name: Package solaris-desktop

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release name'
        required: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  package-solaris-desktop-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run npm install
        run: |
          npm install
      - name: Run npm run make:linux
        run: |
          npm run make:linux
      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: solaris-desktop-linux
          path: out/make/zip/linux/x64/*.zip
          retention-days: 3
  package-solaris-desktop-mac:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run npm install
        run: |
          npm install
      - name: Run npm run make:mac
        run: |
          npm run make:mac
      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: solaris-desktop-mac
          path: out/make/zip/darwin/arm64/*.zip
          retention-days: 3
  package-solaris-desktop-windows:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run npm install
        run: |
          npm install
      - name: Run npm run make:windows
        run: |
          npm run make:windows
      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: solaris-desktop-windows
          path: out/make/zip/win32/x64/*.zip
          retention-days: 3
  release:
    needs: [ package-solaris-desktop-linux, package-solaris-desktop-mac, package-solaris-desktop-windows ]
    if: ${{ inputs.tag != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: solaris-desktop-linux
          path: artifacts/linux

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: solaris-desktop-mac
          path: artifacts/macos

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: solaris-desktop-windows
          path: artifacts/windows

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ inputs.tag }}
          tag_name: ${{ inputs.tag }}
          files: |
            artifacts/linux/**
            artifacts/macos/**
            artifacts/windows/**